### ISSUE TITLE
Cannot Initialize JEP class in eclipse

### ISSUE THREAD

**Issue by WxmanJ** [mrj0/jep#78]
I recently compiled AWIPS from source and didn't run into any issues, but when I run the GUI and try to display observations or anything with derived parameters (that use Python), I keep running into the following errors (below) regarding JEP. JEP is indeed available for use and it shouldn't have compiled if it was not available.

Any thoughts?

Error making Point Data request.com.raytheon.uf.common.inventory.exception.DataCubeException: Error executing Derived Parameter.
    at com.raytheon.uf.common.derivparam.data.DerivedRequestableData.getDataValue(DerivedRequestableData.java:94)
    at com.raytheon.viz.pointdata.util.PointDataCubeAdapter.getPoints(PointDataCubeAdapter.java:155)
    at com.raytheon.viz.pointdata.util.PointDataCubeAdapter.getPoints(PointDataCubeAdapter.java:105)
    at com.raytheon.uf.viz.datacube.DataCubeContainer.getPointData(DataCubeContainer.java:168)
    at com.raytheon.uf.viz.datacube.DataCubeContainer.getPointData(DataCubeContainer.java:176)
    at com.raytheon.viz.pointdata.thread.PlotModelDataRequestJob.requestData(PlotModelDataRequestJob.java:257)
    at com.raytheon.viz.pointdata.thread.PlotModelDataRequestJob.run(PlotModelDataRequestJob.java:132)
    at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
Caused by: java.util.concurrent.ExecutionException: com.raytheon.uf.common.python.concurrent.PythonJobFailedException: Could not initialize class jep.Jep
    at java.util.concurrent.FutureTask.report(FutureTask.java:122)
    at java.util.concurrent.FutureTask.get(FutureTask.java:192)
    at com.raytheon.uf.common.python.concurrent.PythonInterpreterThreadPoolExecutor$PythonListenableFutureTask.get(PythonInterpreterThreadPoolExecutor.java:208)
    at com.raytheon.uf.common.derivparam.python.DerivParamPythonFunctionAdapter.executeFunction(DerivParamPythonFunctionAdapter.java:151)
    at com.raytheon.uf.common.derivparam.library.DerivedParameterGenerator.calculate(DerivedParameterGenerator.java:204)
    at com.raytheon.uf.common.derivparam.data.DerivedRequestableData.getDataValue(DerivedRequestableData.java:86)
    ... 7 more
Caused by: com.raytheon.uf.common.python.concurrent.PythonJobFailedException: Could not initialize class jep.Jep
    at com.raytheon.uf.common.python.concurrent.PythonInterpreterThreadPoolExecutor$PythonListenableFutureTask$1.call(PythonInterpreterThreadPoolExecutor.java:235)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at com.raytheon.uf.common.python.concurrent.PythonInterpreterThreadPoolExecutor$PythonListenableFutureTask.run(PythonInterpreterThreadPoolExecutor.java:219)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
    at com.raytheon.uf.common.python.concurrent.PythonThreadFactory$PythonThread.run(PythonThreadFactory.java:121)
Caused by: java.lang.NoClassDefFoundError: Could not initialize class jep.Jep
    at com.raytheon.uf.common.python.PythonInterpreter.<init>(PythonInterpreter.java:134)
    at com.raytheon.uf.common.python.PythonInterpreter.<init>(PythonInterpreter.java:108)
    at com.raytheon.uf.common.derivparam.python.MasterDerivScript.<init>(MasterDerivScript.java:86)
    at com.raytheon.uf.common.derivparam.python.MasterDerivScriptFactory.createPythonScript(MasterDerivScriptFactory.java:87)
    at com.raytheon.uf.common.derivparam.python.MasterDerivScriptFactory.createPythonScript(MasterDerivScriptFactory.java:1)
    at com.raytheon.uf.common.python.concurrent.PythonThreadFactory$1.initialValue(PythonThreadFactory.java:79)
    at com.raytheon.uf.common.python.concurrent.PythonThreadFactory$1.initialValue(PythonThreadFactory.java:1)
    at java.lang.ThreadLocal.setInitialValue(ThreadLocal.java:180)
    at java.lang.ThreadLocal.get(ThreadLocal.java:170)
    at com.raytheon.uf.common.python.concurrent.PythonInterpreterThreadPoolExecutor$PythonListenableFutureTask$1.call(PythonInterpreterThreadPoolExecutor.java:232)
    ... 6 more

 

 

Error checking if plot is valid for plot model maritimeDesign.svgjava.util.concurrent.ExecutionException: com.raytheon.uf.common.python.concurrent.PythonJobFailedException: Could not initialize class jep.Jep
    at java.util.concurrent.FutureTask.report(FutureTask.java:122)
    at java.util.concurrent.FutureTask.get(FutureTask.java:192)
    at com.raytheon.uf.common.python.concurrent.PythonInterpreterThreadPoolExecutor$PythonListenableFutureTask.get(PythonInterpreterThreadPoolExecutor.java:208)
    at com.raytheon.viz.pointdata.PlotModelFactory.getStationPlot(PlotModelFactory.java:544)
    at com.raytheon.viz.pointdata.thread.PlotModelGeneratorJob.run(PlotModelGeneratorJob.java:94)
    at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
Caused by: com.raytheon.uf.common.python.concurrent.PythonJobFailedException: Could not initialize class jep.Jep
    at com.raytheon.uf.common.python.concurrent.PythonInterpreterThreadPoolExecutor$PythonListenableFutureTask$1.call(PythonInterpreterThreadPoolExecutor.java:235)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at com.raytheon.uf.common.python.concurrent.PythonInterpreterThreadPoolExecutor$PythonListenableFutureTask.run(PythonInterpreterThreadPoolExecutor.java:219)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
    at com.raytheon.uf.common.python.concurrent.PythonThreadFactory$PythonThread.run(PythonThreadFactory.java:121)
Caused by: java.lang.NoClassDefFoundError: Could not initialize class jep.Jep
    at com.raytheon.uf.common.python.PythonInterpreter.<init>(PythonInterpreter.java:134)
    at com.raytheon.uf.common.python.PythonInterpreter.<init>(PythonInterpreter.java:88)
    at com.raytheon.uf.common.python.PythonScript.<init>(PythonScript.java:90)
    at com.raytheon.viz.pointdata.python.PlotPythonScript.<init>(PlotPythonScript.java:70)
    at com.raytheon.viz.pointdata.python.PlotPythonScriptFactory.createPythonScript(PlotPythonScriptFactory.java:117)
    at com.raytheon.viz.pointdata.python.PlotPythonScriptFactory.createPythonScript(PlotPythonScriptFactory.java:1)
    at com.raytheon.uf.common.python.concurrent.PythonThreadFactory$1.initialValue(PythonThreadFactory.java:79)
    at com.raytheon.uf.common.python.concurrent.PythonThreadFactory$1.initialValue(PythonThreadFactory.java:1)
    at java.lang.ThreadLocal.setInitialValue(ThreadLocal.java:180)
    at java.lang.ThreadLocal.get(ThreadLocal.java:170)
    at com.raytheon.uf.common.python.concurrent.PythonInterpreterThreadPoolExecutor$PythonListenableFutureTask$1.call(PythonInterpreterThreadPoolExecutor.java:232)
    ... 6 more

Error making Point Data request.com.raytheon.uf.common.inventory.exception.DataCubeException: Error executing Derived Parameter.
    at com.raytheon.uf.common.derivparam.data.DerivedRequestableData.getDataValue(DerivedRequestableData.java:94)
    at com.raytheon.viz.pointdata.util.PointDataCubeAdapter.getPoints(PointDataCubeAdapter.java:155)
    at com.raytheon.viz.pointdata.util.PointDataCubeAdapter.getPoints(PointDataCubeAdapter.java:105)
    at com.raytheon.uf.viz.datacube.DataCubeContainer.getPointData(DataCubeContainer.java:168)
    at com.raytheon.uf.viz.datacube.DataCubeContainer.getPointData(DataCubeContainer.java:176)
    at com.raytheon.viz.pointdata.thread.PlotModelDataRequestJob.requestData(PlotModelDataRequestJob.java:257)
    at com.raytheon.viz.pointdata.thread.PlotModelDataRequestJob.run(PlotModelDataRequestJob.java:132)
    at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
Caused by: java.util.concurrent.ExecutionException: com.raytheon.uf.common.python.concurrent.PythonJobFailedException: Could not initialize class jep.Jep
    at java.util.concurrent.FutureTask.report(FutureTask.java:122)
    at java.util.concurrent.FutureTask.get(FutureTask.java:192)
    at com.raytheon.uf.common.python.concurrent.PythonInterpreterThreadPoolExecutor$PythonListenableFutureTask.get(PythonInterpreterThreadPoolExecutor.java:208)
    at com.raytheon.uf.common.derivparam.python.DerivParamPythonFunctionAdapter.executeFunction(DerivParamPythonFunctionAdapter.java:151)
    at com.raytheon.uf.common.derivparam.library.DerivedParameterGenerator.calculate(DerivedParameterGenerator.java:204)
    at com.raytheon.uf.common.derivparam.data.DerivedRequestableData.getDataValue(DerivedRequestableData.java:86)
    ... 7 more
Caused by: com.raytheon.uf.common.python.concurrent.PythonJobFailedException: Could not initialize class jep.Jep
    at com.raytheon.uf.common.python.concurrent.PythonInterpreterThreadPoolExecutor$PythonListenableFutureTask$1.call(PythonInterpreterThreadPoolExecutor.java:235)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at com.raytheon.uf.common.python.concurrent.PythonInterpreterThreadPoolExecutor$PythonListenableFutureTask.run(PythonInterpreterThreadPoolExecutor.java:219)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
    at com.raytheon.uf.common.python.concurrent.PythonThreadFactory$PythonThread.run(PythonThreadFactory.java:121)
Caused by: java.lang.NoClassDefFoundError: Could not initialize class jep.Jep
    at com.raytheon.uf.common.python.PythonInterpreter.<init>(PythonInterpreter.java:134)
    at com.raytheon.uf.common.python.PythonInterpreter.<init>(PythonInterpreter.java:108)
    at com.raytheon.uf.common.derivparam.python.MasterDerivScript.<init>(MasterDerivScript.java:86)
    at com.raytheon.uf.common.derivparam.python.MasterDerivScriptFactory.createPythonScript(MasterDerivScriptFactory.java:87)
    at com.raytheon.uf.common.derivparam.python.MasterDerivScriptFactory.createPythonScript(MasterDerivScriptFactory.java:1)
    at com.raytheon.uf.common.python.concurrent.PythonThreadFactory$1.initialValue(PythonThreadFactory.java:79)
    at com.raytheon.uf.common.python.concurrent.PythonThreadFactory$1.initialValue(PythonThreadFactory.java:1)
    at java.lang.ThreadLocal.setInitialValue(ThreadLocal.java:180)
    at java.lang.ThreadLocal.get(ThreadLocal.java:170)
    at com.raytheon.uf.common.python.concurrent.PythonInterpreterThreadPoolExecutor$PythonListenableFutureTask$1.call(PythonInterpreterThreadPoolExecutor.java:232)
    ... 6 more

 

 

Error checking if plot is valid for plot model maritimeDesign.svgjava.util.concurrent.ExecutionException: com.raytheon.uf.common.python.concurrent.PythonJobFailedException: Could not initialize class jep.Jep
    at java.util.concurrent.FutureTask.report(FutureTask.java:122)
    at java.util.concurrent.FutureTask.get(FutureTask.java:192)
    at com.raytheon.uf.common.python.concurrent.PythonInterpreterThreadPoolExecutor$PythonListenableFutureTask.get(PythonInterpreterThreadPoolExecutor.java:208)
    at com.raytheon.viz.pointdata.PlotModelFactory.getStationPlot(PlotModelFactory.java:544)
    at com.raytheon.viz.pointdata.thread.PlotModelGeneratorJob.run(PlotModelGeneratorJob.java:94)
    at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
Caused by: com.raytheon.uf.common.python.concurrent.PythonJobFailedException: Could not initialize class jep.Jep
    at com.raytheon.uf.common.python.concurrent.PythonInterpreterThreadPoolExecutor$PythonListenableFutureTask$1.call(PythonInterpreterThreadPoolExecutor.java:235)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at com.raytheon.uf.common.python.concurrent.PythonInterpreterThreadPoolExecutor$PythonListenableFutureTask.run(PythonInterpreterThreadPoolExecutor.java:219)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
    at com.raytheon.uf.common.python.concurrent.PythonThreadFactory$PythonThread.run(PythonThreadFactory.java:121)
Caused by: java.lang.NoClassDefFoundError: Could not initialize class jep.Jep
    at com.raytheon.uf.common.python.PythonInterpreter.<init>(PythonInterpreter.java:134)
    at com.raytheon.uf.common.python.PythonInterpreter.<init>(PythonInterpreter.java:88)
    at com.raytheon.uf.common.python.PythonScript.<init>(PythonScript.java:90)
    at com.raytheon.viz.pointdata.python.PlotPythonScript.<init>(PlotPythonScript.java:70)
    at com.raytheon.viz.pointdata.python.PlotPythonScriptFactory.createPythonScript(PlotPythonScriptFactory.java:117)
    at com.raytheon.viz.pointdata.python.PlotPythonScriptFactory.createPythonScript(PlotPythonScriptFactory.java:1)
    at com.raytheon.uf.common.python.concurrent.PythonThreadFactory$1.initialValue(PythonThreadFactory.java:79)
    at com.raytheon.uf.common.python.concurrent.PythonThreadFactory$1.initialValue(PythonThreadFactory.java:1)
    at java.lang.ThreadLocal.setInitialValue(ThreadLocal.java:180)
    at java.lang.ThreadLocal.get(ThreadLocal.java:170)
    at com.raytheon.uf.common.python.concurrent.PythonInterpreterThreadPoolExecutor$PythonListenableFutureTask$1.call(PythonInterpreterThreadPoolExecutor.java:232)
    ... 6 more

**Comment by ndjensen** [comment]
This is not an appropriate place to seek A2 assistance.

Your underlying error is `Caused by: java.lang.NoClassDefFoundError: Could not initialize class jep.Jep`.  A NoClassDefFoundError usually implies that a static variable or block in the code failed to initialize.  My guess would be this static block: https://github.com/mrj0/jep/blob/dev_3.6/src/jep/Jep.java#L205  You can set a breakpoint in there, launch in debug mode, and see if that block succeeds or fails.  See https://github.com/mrj0/jep/wiki/FAQ#how-do-i-fix-unsatisfied-link-error-no-jep-in-javalibrarypath for assistance with that error.

If that is the error, I don't know why the exception didn't give more information.  In Eclipse you can set `-Djava.library.path` in the .product file or in the Run Configuration dialog you can set LD_LIBRARY_PATH (presuming you are on Linux).

**Comment by WxmanJ** [comment]
Thank you for your assistance on this.

Originally, I was not sure if the issue was specific to A2 or Jep-related, but I do appreciate the clarification.
