### ISSUE TITLE
java.lang.UnsatisfiedLinkError: ...\Python36\Lib\site-packages\jep\jep.dll: %1 is not a valid Win32 application

### ISSUE THREAD

**Issue by omerth** [mrj0/jep#83]
I am getting an error when trying to use Jep from Java.

```
    String DIR = "C:\\Program Files\\Python\\Python36\\Lib\\site-packages\\jep";
    System.setProperty("java.library.path", DIR);
    // Following three lines were necessary, otherwise the classloader was unable to find the library
    final Field fieldSysPath = ClassLoader.class.getDeclaredField("sys_paths");
    fieldSysPath.setAccessible(true);
    fieldSysPath.set(null, null);

    Jep jep = new Jep(false);
```
The error is thrown in the last line above. This is the stacktrace:
```
Exception in thread "main" java.lang.UnsatisfiedLinkError: C:\Program Files\Python\Python36\Lib\site-packages\jep\jep.dll: %1 is not a valid Win32 application
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1941)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1857)
	at java.lang.Runtime.loadLibrary0(Runtime.java:870)
	at java.lang.System.loadLibrary(System.java:1122)
	at jep.Jep.<clinit>(Jep.java:206)
	at Jepping.main(Jepping.java:19)
```
I'm using Windows 10 64 bit, Java 8 64 bit, Python 3.6.1 64 bit, and installed jep using 'pip install jep', and seemingly everything went fine.

Thank you for the help

**Comment by omerth** [comment]
Hello - The issue has been resolved.
I had been running the above code from the IntelliJ IDE.  I was using 32-bit IntelliJ.  I switched to the 64-bit IntelliJ and now the issue is resolved.
Thanks.
